version: "3.9"
services:
  my-web-app:
    container_name: "django-todo-app"
    build: .
    ports:
      - 9000:9000 
    volumes:
      - django-todo-volume:/data
  my-db:
    container_name: "django-mysql-db"
    image: mysql:5.7
    ports:
        - 3306:3306
    environment:
          MYSQL_ROOT_PASSWORD: "test@123"
  my-nginx:
    container_name: "njinx"
    image: nginx:latest
    ports:
      - 80:80   
volumes:
    django-todo-volume:
